<?xml version="1.0"?>
<package format="3"><name>avm_bringup</name><version>0.1.0</version><description>AVM simulation avm_bringup</description><maintainer email="dev@example.com">AVM Developers</maintainer><license>Apache-2.0</license><buildtool_depend>ament_python</buildtool_depend><exec_depend>launch</exec_depend><exec_depend>launch_ros</exec_depend><exec_depend>scene_manager</exec_depend><exec_depend>scene_editor</exec_depend><exec_depend>gs_renderer</exec_depend><exec_depend>avm_stitcher</exec_depend><test_depend>python3-pytest</test_depend><export><build_type>ament_python</build_type></export></package>

